apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-pvc-csi-1
spec:
  dataSource:
    name: snap-csi-1
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: sc-csi-1