apiVersion: v1
kind: Secret
metadata:
  name: nimble-secret
stringData:
  serviceName: nimble-csp-svc
  servicePort: "8080"
  backend: 192.168.1.1
  username: admin
data:
  # echo -n admin | base64
  password: YWRtaW4=
